# Generated by Django 3.2.15 on 2022-10-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='club',
            field=models.CharField(choices=[('Manchester', 'Manchester'), ('Arsenal', 'Arsenal'), ('Liverpool', 'Liverpool'), ('Chelsea', 'Chelsea')], default='', max_length=50),
        ),
    ]
