# Generated by Django 3.2.15 on 2022-10-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='club',
            field=models.CharField(default='', max_length=50),
        ),
    ]
