# Generated by Django 3.2.15 on 2022-10-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='club',
            field=models.CharField(choices=[('', ''), ('Manchester', 'Manchester'), ('Arsenal', 'Arsenal'), ('Liverpool', 'Liverpool'), ('Chelsea', 'Chelsea')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic/'),
        ),
    ]
