# Generated by Django 3.2.15 on 2022-10-19 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20221015_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='club',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='club_icon',
        ),
        migrations.AddField(
            model_name='profile',
            name='Afcon',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.afconleague'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Baseball',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.baseball'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Bundesliga',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.bundesliga'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Europa',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.europaleague'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Formula1',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.formula1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Laliga',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.laliga'),
        ),
        migrations.AddField(
            model_name='profile',
            name='NBA',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.nba'),
        ),
        migrations.AddField(
            model_name='profile',
            name='NFL',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.nfl'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Worldcup',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.worldcup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='clubimage',
            field=models.ImageField(choices=[('', ''), ('Manchester', 'Manchester'), ('Arsenal', 'Arsenal'), ('Liverpool', 'Liverpool'), ('Chelsea', 'Chelsea')], default='Manchester', max_length=220, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
