# Generated by Django 3.2.15 on 2022-10-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221014_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
